sequenceDiagram
    participant Buyer1
    participant Seller
    participant Buyer2
    Buyer1 ->> Seller: title
    par
        Seller ->> Buyer1: quote
        Seller ->> Buyer2: quote
    end
    Buyer1 ->> Buyer2: quote div 2
    alt 
        Buyer2 -->> Seller: ok
        Buyer2 ->> Seller: address
        Seller ->> Buyer2: date
    else
        Buyer2 -->> Seller: quit
    end
