sequenceDiagram
    participant Buyer1
    participant Seller
    participant Buyer2
    Buyer1 ->> Seller: title
    Seller ->> Buyer1: quote
    Buyer1 ->> Buyer2: share
    alt 
        Buyer2 -->> Seller: ok
        Buyer2 ->> Seller: address
        Seller ->> Buyer2: date
    else
        Buyer2 -->> Seller: quit
    end
